<template>
  <BaseBody >
    <div>
      <div>소속 보험사 또는 GA를 선택해 주세요</div>
      <button
        style="border-bottom: 1px solid gray; padding: 1rem 3rem"
        :style="selectedTab === 'ga' ? 'border-bottom: 3px solid blue' : ''"
        @click="clickTab('ga')"
      >
        GA
      </button>
      <button
        style="border-bottom: 1px solid gray; padding: 1rem 3rem"
        :style="selectedTab === 'insuranceCompany' ? 'border-bottom: 3px solid blue' : ''"
        @click="clickTab('insuranceCompany')"
      >
        보험사
      </button>
      <div style="padding: 1rem">
        <div v-show="selectedTab === 'ga'" style="display: flex; flex-direction: column; gap: 1rem">
          <input
            type="text"
            style="padding: 0.25rem; border: 1px solid gainsboro"
            placeholder="GA명이나 주소를 검색해주세요"
          />

          <div
            v-for="item in gaList"
            :key="item.id"
            style="display: flex; align-items: center; gap: 3rem; border-top: 1px solid gainsboro"
            @click="clickAgency(item)"
          >
            <div style="padding: 0.75rem 0">
              <div>{{ item.label }}</div>
              <div>{{ item.address }}</div>
            </div>
            <div><i class="ri-arrow-right-s-line"></i></div>
          </div>

          <div style="padding: 1rem; border: 1px solid gainsboro; text-align: center">
            <div>소속된 GA가 없나요?</div>
            <button style="border: 1px solid gray; padding: 0.25rem" @click="clickRegisterGA">직접 찾기</button>
          </div>
        </div>
        <div v-show="selectedTab === 'insuranceCompany'">
          <div v-for="item in insuList" :key="item.insuId">
            <div>
              <img :src="item.logoUrl" alt="" style="width: 40px" />
              {{ item.insuDispNm }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </BaseBody>
</template>

<script setup lang="ts">
import { ConfirmModal, AlertModal } from '@lemonhc/fo-ui/components/modal'
import BaseBody from '~/components/layout/BaseBody.vue'

const selectedTab = ref('ga')
const gaList = ref([
  {
    id: 1,
    label: 'GA1',
    type: 'ga',
    address: '서울 영등포구 국제금융로 66길 33 여의도동'
  },
  {
    id: 2,
    label: 'GA2',
    type: 'ga',
    address: '서울 영등포구 국제금융로 66길 33 여의도동'
  },
  {
    id: 3,
    label: 'GA3',
    type: 'ga',
    address: '서울 영등포구 국제금융로 66길 33 여의도동'
  }
])

const clickTab = (type: 'ga' | 'insuranceCompany') => {
  selectedTab.value = type
}

const clickAgency = async item => {
  const modalContent = `
    <div>
      <div>
        <i class="ri-information-line"></i>
      </div>
      <div>[${item.type}] ${item.label}</div>
      <div>보험설계사용 서비스에 가입하시겠어요?</div>
    </div>`

  const alertModalContent = `
    <div>
      <div>
        <i class="ri-information-line"></i>
      </div>
      <div>가입을 완료했어요.</div>
      <div>보험설계사용 서비스 이용을 위해<br /> 다시 로그인 해주세요.</div>
    </div>`

  ConfirmModal.open({
    isVisible: true,
    html: modalContent,
    confirmButtonText: '가입하기',
    isShowCancelButton: false
  }).then(res => {
    console.log('eeee', res)
    if (res) {
      ConfirmModal.open({
        isVisible: true,
        html: alertModalContent,
        confirmButtonText: '로그인하기',
        isShowCancelButton: false
      })
    }
  })
}

const insuList = ref([
  {
    insuId: 2,
    insuCompCd: 'KBINS',
    insuCompNm: 'KB손해보험',
    insuShortNm: 'KB손해보험',
    insuDispNm: 'KB손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/KBINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'FILE',
    anymSendType: 'FILE',
    guideFaxTxt: '',
    callCenterTel: '1544-0114',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 1,
    insuCompCd: 'SAMSUNGFIRE',
    insuCompNm: '삼성화재해상보험',
    insuShortNm: '삼성화재',
    insuDispNm: '삼성화재',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/SAMSUNGFIRE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FILE',
    anymSendType: 'FILE',
    guideFaxTxt: null,
    callCenterTel: '1588-5114',
    autoTranEnabled: false,
    pharmEnabled: false,
    insuFax: '0508-924-1389',
    inpatientEnabled: true,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'TERM',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 3,
    insuCompCd: 'NHINS',
    insuCompNm: 'NH농협손해보험',
    insuShortNm: 'NH농협손해보험',
    insuDispNm: 'NH농협손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/NHINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'EDI',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1644-9000',
    autoTranEnabled: true,
    pharmEnabled: false,
    insuFax: '0508-924-1389',
    inpatientEnabled: true,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: false,
    qabContractCheck: 'TERM',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: true,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 10,
    insuCompCd: 'HEUNGKUKFIRE',
    insuCompNm: '흥국화재해상보험',
    insuShortNm: '흥국화재',
    insuDispNm: '흥국화재',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/HEUNGKUKFIRE.svg',
    myInsuEnabled: true,
    mbrSendType: 'EDI',
    anymSendType: 'FILE',
    guideFaxTxt: '',
    callCenterTel: '1688-1688',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 11,
    insuCompCd: 'HIFIRE',
    insuCompNm: '현대해상화재보험',
    insuShortNm: '현대해상',
    insuDispNm: '현대해상',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/HIFIRE.svg',
    myInsuEnabled: true,
    mbrSendType: 'FILE',
    anymSendType: 'FILE',
    guideFaxTxt: '',
    callCenterTel: '1588-5656',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: true,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'TERM',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 12,
    insuCompCd: 'IDBINS',
    insuCompNm: 'DB손해보험',
    insuShortNm: 'DB손해보험',
    insuDispNm: 'DB손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/IDBINS.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-0100',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 6,
    insuCompCd: 'MERITZFIRE',
    insuCompNm: '메리츠화재해상보험',
    insuShortNm: '메리츠화재',
    insuDispNm: '메리츠화재',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/MERITZFIRE.svg',
    myInsuEnabled: true,
    mbrSendType: 'FILE',
    anymSendType: 'FILE',
    guideFaxTxt: null,
    callCenterTel: '1566-7711',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'TERM',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 7,
    insuCompCd: 'HANWHAINS',
    insuCompNm: '한화손해보험',
    insuShortNm: '한화손해보험',
    insuDispNm: '한화손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/HANWHAINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'EMAIL',
    anymSendType: 'EMAIL',
    guideFaxTxt: null,
    callCenterTel: '1566-8000',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 8,
    insuCompCd: 'LOTTEINS',
    insuCompNm: '롯데손해보험',
    insuShortNm: '롯데손해보험',
    insuDispNm: '롯데손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/LOTTEINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-3344',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 9,
    insuCompCd: 'MGINS',
    insuCompNm: 'MG손해보험',
    insuShortNm: 'MG손해보험',
    insuDispNm: 'MG손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/MGINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-5959',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 13,
    insuCompCd: 'AXAINS',
    insuCompNm: 'AXA손해보험',
    insuShortNm: 'AXA손해보험',
    insuDispNm: 'AXA손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/AXAINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt:
      '① <strong>5번</strong>(상해/질병/운전자보험 보험금 청구)<br>\r\n② <strong>1번</strong>(운전자/화재/상해/건강보험)<br>\r\n③ 가입 고객님의 <strong>주민등록번호 입력</strong><br>\r\n④ <strong>상담원 통화</strong>\r\n',
    callCenterTel: '1566-1566',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: null,
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 14,
    insuCompCd: 'AIGINS',
    insuCompNm: 'AIG손해보험',
    insuShortNm: 'AIG손해보험',
    insuDispNm: 'AIG손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/AIGINS.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1544-2792',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 15,
    insuCompCd: 'EDUCARINS',
    insuCompNm: '하나손해보험',
    insuShortNm: '하나손해보험',
    insuDispNm: '하나손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/EDUCARINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1566-3000',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 16,
    insuCompCd: 'CUBBINS',
    insuCompNm: '라이나손해보험',
    insuShortNm: '라이나손해보험',
    insuDispNm: '라이나손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/CUBBINS.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1566-5800',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 5,
    insuCompCd: 'NHLIFE',
    insuCompNm: 'NH농협생명보험',
    insuShortNm: 'NH농협생명',
    insuDispNm: 'NH농협생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/NHLIFE.svg',
    myInsuEnabled: true,
    mbrSendType: 'EDI',
    anymSendType: 'FAX',
    guideFaxTxt: '',
    callCenterTel: '1544-4000',
    autoTranEnabled: false,
    pharmEnabled: false,
    insuFax: '0508-924-1389',
    inpatientEnabled: true,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: false,
    qabContractCheck: 'TERM',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: true,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: false
  },
  {
    insuId: 4,
    insuCompCd: 'MIRAELIFE',
    insuCompNm: '미래에셋생명',
    insuShortNm: '미래에셋생명',
    insuDispNm: '미래에셋생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/MIRAELIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: '',
    callCenterTel: '1588-0220',
    autoTranEnabled: false,
    pharmEnabled: false,
    insuFax: '',
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 29,
    insuCompCd: 'SHINHLIFE',
    insuCompNm: '신한라이프',
    insuShortNm: '신한라이프',
    insuDispNm: '신한라이프',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/SHINHLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt:
      '① <strong>1번(구 신한생명 고객)</strong> 또는 <strong>2번(구 오렌지라이프 고객)</strong><br>\r\n② <strong>0번</strong> (상담사 통화 연결)<br>\r\n③ 빠른 상담은 <strong>휴대폰번호 + # 입력</strong> (입력 원치않으면 #)<br>\r\n④ <strong>1번</strong> (보험 조회/변경 및 일반상담)\r\n',
    callCenterTel: '1588-5580',
    autoTranEnabled: true,
    pharmEnabled: false,
    insuFax: '-',
    inpatientEnabled: true,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 27,
    insuCompCd: 'METLIFE',
    insuCompNm: '메트라이프생명',
    insuShortNm: '메트라이프생명',
    insuDispNm: '메트라이프생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/METLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-9600',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 21,
    insuCompCd: 'HEUNGKUKLIFE',
    insuCompNm: '흥국생명',
    insuShortNm: '흥국생명',
    insuDispNm: '흥국생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/HEUNGKUKLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-2288',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '',
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 20,
    insuCompCd: 'SAMSUNGLIFE',
    insuCompNm: '삼성생명',
    insuShortNm: '삼성생명',
    insuDispNm: '삼성생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/SAMSUNGLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt:
      '① <strong>1번</strong> (음성 ARS)<br>\r\n② <strong>1번</strong> (본인 맞으면), <strong>2번</strong> (본인 아니면)<br>\r\n③ <strong>0번</strong> (상담사 연결)\r\n',
    callCenterTel: '1588-3114',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: null,
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 22,
    insuCompCd: 'KYOBOLIFE',
    insuCompNm: '교보생명',
    insuShortNm: '교보생명',
    insuDispNm: '교보생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/KYOBOLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt:
      '① <strong>2번</strong> (누르는 ARS)<br>\r\n② <strong>0번</strong> (상담원 연결)<br>\r\n③ <strong>2번</strong> (수술,입원 장애 실손관련 보험금 상담)<br>\r\n④ <strong>주민등록번호 입력</strong> (입력 원치않으면 *)\r\n',
    callCenterTel: '1588-1001',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: null,
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 18,
    insuCompCd: 'HANWHALIFE',
    insuCompNm: '한화생명',
    insuShortNm: '한화생명',
    insuDispNm: '한화생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/HANWHALIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'EDI',
    anymSendType: 'FAX',
    guideFaxTxt:
      '① <strong>1번</strong> (본인 맞으면), <strong>2번</strong> (본인 아니면)<br>\r\n② <strong>0번</strong> (상담사 연결)<br>\r\n③ <strong>0번</strong> (기타 상담)<br>\r\n④ <strong>주민등록번호 입력</strong> (입력 원치않으면 #)\r\n',
    callCenterTel: '1588-6363',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: null,
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 19,
    insuCompCd: 'ABLLIFE',
    insuCompNm: 'ABL생명',
    insuShortNm: 'ABL생명',
    insuDispNm: 'ABL생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/ABLLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-4404',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 23,
    insuCompCd: 'DGBLIFE',
    insuCompNm: 'IM라이프생명보험',
    insuShortNm: 'IM라이프생명보험',
    insuDispNm: 'IM라이프생명보험',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/DGBLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-4770',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 24,
    insuCompCd: 'KDBLIFE',
    insuCompNm: 'KDB생명',
    insuShortNm: 'KDB생명',
    insuDispNm: 'KDB생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/KDBLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-4040',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 25,
    insuCompCd: 'DBLIFE',
    insuCompNm: 'DB생명',
    insuShortNm: 'DB생명',
    insuDispNm: 'DB생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/DBLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-3131',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 26,
    insuCompCd: 'DYLIFE',
    insuCompNm: '동양생명',
    insuShortNm: '동양생명',
    insuDispNm: '동양생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/DYLIFE.svg',
    myInsuEnabled: true,
    mbrSendType: 'EDI',
    anymSendType: 'FILE',
    guideFaxTxt: '',
    callCenterTel: '1577-1004',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'TERM',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 30,
    insuCompCd: 'CHUBBLIFE',
    insuCompNm: '처브라이프생명',
    insuShortNm: '처브라이프생명',
    insuDispNm: '처브라이프생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/CHUBBLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1566-5800',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 32,
    insuCompCd: 'HANALIFE',
    insuCompNm: '하나생명',
    insuShortNm: '하나생명',
    insuDispNm: '하나생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/HANALIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1577-1112',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '',
    inpatientEnabled: false,
    faxNoRequired: true,
    faxNoRequiredPhoto: true,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 33,
    insuCompCd: 'CARDIFLIFE',
    insuCompNm: 'BNP파리바카디프생명보험',
    insuShortNm: '카디프생명',
    insuDispNm: '카디프생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/CARDIFLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1688-1118',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 34,
    insuCompCd: 'FUBONLIFE',
    insuCompNm: '푸본현대생명',
    insuShortNm: '푸본현대생명',
    insuDispNm: '푸본현대생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/FUBONLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1577-3311',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 35,
    insuCompCd: 'LINALIFE',
    insuCompNm: '라이나생명',
    insuShortNm: '라이나생명',
    insuDispNm: '라이나생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/LINALIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-0058',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 36,
    insuCompCd: 'AIALIFE',
    insuCompNm: 'AIA생명',
    insuShortNm: 'AIA생명',
    insuDispNm: 'AIA생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/AIALIFE.svg',
    myInsuEnabled: true,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-9898',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 37,
    insuCompCd: 'KBLIFE',
    insuCompNm: 'KB생명보험',
    insuShortNm: 'KB생명보험',
    insuDispNm: 'KB생명보험',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/KBLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1588-9922',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 38,
    insuCompCd: 'POSTINS',
    insuCompNm: '우체국보험',
    insuShortNm: '우체국보험',
    insuDispNm: '우체국보험',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/POSTINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'EDI',
    anymSendType: 'FILE',
    guideFaxTxt: null,
    callCenterTel: '1599-0100',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'TERM',
    picContractCheck: 'TERM',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: true,
    picDiseaseNameInput: true,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 39,
    insuCompCd: 'PLANETLIFE',
    insuCompNm: '교보라이프플래닛생명',
    insuShortNm: '교보라이프플래닛생명',
    insuDispNm: '교보라이프플래닛생명',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/PLANETLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1566-0999',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 40,
    insuCompCd: 'TKYOLIFE',
    insuCompNm: '교직원공제회보험',
    insuShortNm: '교직원공제회보험',
    insuDispNm: '교직원공제회보험',
    insuCompType: 'L',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/TKYOLIFE.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1577-3400',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 41,
    insuCompCd: 'CARROTINS',
    insuCompNm: '캐롯손해보험',
    insuShortNm: '캐롯손해보험',
    insuDispNm: '캐롯손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/CARROTINS.svg',
    myInsuEnabled: true,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1566-0300',
    autoTranEnabled: true,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  },
  {
    insuId: 42,
    insuCompCd: 'SHINHEZ',
    insuCompNm: '신한EZ손해보험',
    insuShortNm: '신한EZ손해보험',
    insuDispNm: '신한EZ손해보험',
    insuCompType: 'I',
    logoUrl: 'https://cache.lemonhc.com/thumnail/insu/SHINHEZ.svg',
    myInsuEnabled: false,
    mbrSendType: 'FAX',
    anymSendType: 'FAX',
    guideFaxTxt: null,
    callCenterTel: '1544-2580',
    autoTranEnabled: false,
    pharmEnabled: true,
    insuFax: '0508-924-1389',
    inpatientEnabled: false,
    faxNoRequired: false,
    faxNoRequiredPhoto: false,
    inpatientDiagRequired: true,
    qabContractCheck: 'N/A',
    picContractCheck: 'N/A',
    breakMemo: null,
    onlyEdiEnabled: false,
    picDiseaseCodeInput: false,
    picDiseaseNameInput: false,
    hiwebnetClaimEnabled: true
  }
])

const clickRegisterGA = () => {
  navigateTo('/insu/claim/subrogation/requestGARegister')
}
</script>

<style scoped lang="scss"></style>
